#cloud-config
package_update: true
package_upgrade: true

runcmd:
 - [ sh, -c, echo "=========Installing Microk8s (latest version)=========" ] 
 - sudo snap install microk8s --channel=latest/stable --classic
 - sudo usermod -a -G microk8s ubuntu
 - echo "alias k=microk8s.kubectl" >> /home/ubuntu/.bashrc
 - microk8s enable dashboard dns registry istio

 - [ sh, -c, echo "=========What did we just install=========" ] 
 - [ sh, -c, echo "space on root folder:" ] 
 - [ sh, -c, df -h / ] 
 - [ sh, -c, echo "Testing Microk8s:" ] 
 - [ sh, -c, microk8s.kubectl version  ] 

final_message: "The system is finally up, after $UPTIME seconds"



# Where are the logs?
# Cloud-init uses two files to log to:
# /var/log/cloud-init-output.log: captures the output from each stage of cloud-init when it runs
# /var/log/cloud-init.log: very detailed log with debugging output, detailing each action taken
# /run/cloud-init: contains logs about how cloud-init decided to enable or disable itself, as well as what platforms/datasources were detected. These logs are most useful when trying to determine what cloud-init ran or did not run.

# How to launch it: 
# multipass launch --name highlander --cloud-init ./cloud-init-microk8s.yaml --cpus 4 --memory 4G --disk 10G
# multipass stop highlander
# multipass delete highlander
# multipass purge

